name: Assignment1

on: push
jobs:
    assignment-check-1:
        name: week1
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            - run: |
                   python3 -m pip install numpy
                   ./submit.bat
