name: Assignment1

on: push
jobs:
    tests:
        name: week1
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.5, 3.6, 3.7, 3.8]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.x
              uses: actions/setup-python@v2
              with:
                python-version: '3.7'
                architecture: 'x64'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Assignment check
              run: ./submit.bat
